name: SharpEdge Data Pull

on:
  workflow_dispatch:          # run manually
  schedule:
    - cron: "*/30 * * * *"    # every 30 minutes (adjust as you like)

permissions:
  contents: write             # allow commits back to this repo

jobs:
  pull_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # use GITHUB_TOKEN to push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil pyyaml pandas

      - name: Pull MLB schedule (no API key required)
        run: |
          python - << 'PY'
          import os, json
          from datetime import datetime, timezone
          import requests
          today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
          url = f"https://statsapi.mlb.com/api/v1/schedule?sportId=1&date={today}"
          r = requests.get(url, timeout=60)
          r.raise_for_status()
          data = r.json()
          out_dir = "data/raw/mlb"
          os.makedirs(out_dir, exist_ok=True)
          out_path = f"{out_dir}/schedule_{today}.json"
          with open(out_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
          print(f"Wrote {out_path}")
          PY

      - name: Commit & push data
        run: |
          git config user.name  "sharpedge-bot"
          git config user.email "sharpedge-bot@users.noreply.github.com"
          git add data/raw/mlb/*.json || true
          git commit -m "chore(data): mlb schedule auto-pull" || echo "No changes to commit"
          git push
