name: SharpEdge NBA Data Pull

on:
  workflow_dispatch:
  schedule:
    - cron: "*/45 * * * *"  # every 45 minutes

permissions:
  contents: write

jobs:
  pull_nba_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Pull NBA games (BallDontLie API)
        run: |
          python - <<'PY'
          import os, json, requests
          from datetime import date
          today = date.today().isoformat()
          url = f"https://www.balldontlie.io/api/v1/games?dates[]={today}"
          r = requests.get(url, timeout=60)
          r.raise_for_status()
          data = r.json()
          os.makedirs("data/raw/nba", exist_ok=True)
          out_path = f"data/raw/nba/games_{today}.json"
          with open(out_path, "w") as f:
              json.dump(data, f, indent=2)
          print(f"[NBA] wrote {out_path}")
          PY

      - name: Commit & push NBA data
        run: |
          git config user.name "sharpedge-bot"
          git config user.email "sharpedge-bot@users.noreply.github.com"
          git add data/raw/nba/*.json || true
          git commit -m "chore(data): nba games auto-pull" || echo "No NBA changes"
          git push
